//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTypeChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTypeChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG2000 image files,00 00 00 0C 6A 50 20 20,JP2
        ///3GPP multimedia files,00 00 00 14 66 74 79 70,3GP
        ///MPEG-4 v1,00 00 00 14 66 74 79 70 69 73 6F 6D,MP4
        ///3rd Generation Partnership Project 3GPP,00 00 00 14 66 74 79 70,3GG|3GP|3G2
        ///Windows Disk Image,00 00 00 00 14 00 00 00,TBI
        ///MPEG-4 video_1,00 00 00 18 66 74 79 70,3GP5|M4V|MP4
        ///MPEG-4 video_2,00 00 00 1C 66 74 79 70,MP4
        ///3GPP2 multimedia files,00 00 00 20 66 74 79 70,3GP
        ///Apple audio and video,00 00 00 20 66 74 79 70 4D 34 41,M4A
        ///3rd Generation Partnership Project  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FILESIGNATURES {
            get {
                return ResourceManager.GetString("FILESIGNATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        /// {
        ///   &quot;FileTypeDescriptions&quot;: [ &quot;JPEG2000 image files&quot;],
        ///   &quot;SegmentBytes&quot;: [ &quot;00 00 00 0C 6A 50 20 20&quot;],
        ///   &quot;Extensions&quot;: [ &quot;JP2&quot;]
        /// },
        /// {
        ///   &quot;FileTypeDescriptions&quot;: [ &quot;3GPP multimedia files&quot;],
        ///   &quot;SegmentBytes&quot;: [ &quot;00 00 00 14 66 74 79 70&quot;],
        ///   &quot;Extensions&quot;: [ &quot;3GP&quot;]
        /// },
        /// {
        ///   &quot;FileTypeDescriptions&quot;: [ &quot;MPEG-4 v1&quot;],
        ///   &quot;SegmentBytes&quot;: [ &quot;00 00 00 14 66 74 79 70 69 73 6F 6D&quot;],
        ///   &quot;Extensions&quot;: [ &quot;MP4&quot;]
        /// },
        /// {
        ///   &quot;FileTypeDescriptions&quot;: [ &quot;3rd Generation Partnership Project 3GPP&quot;],
        ///   &quot;Se [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FILESIGNATURES_JSON {
            get {
                return ResourceManager.GetString("FILESIGNATURES_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;FileTypeDescriptions&quot;: [
        ///      &quot;JPEG2000 image files&quot;
        ///    ],
        ///    &quot;SegmentBytes&quot;: [
        ///      &quot;00 00 00 0C 6A 50 20 20&quot;
        ///    ],
        ///    &quot;Extensions&quot;: [
        ///      &quot;JP2&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;FileTypeDescriptions&quot;: [
        ///      &quot;3GPP multimedia files&quot;
        ///    ],
        ///    &quot;SegmentBytes&quot;: [
        ///      &quot;00 00 00 14 66 74 79 70&quot;
        ///    ],
        ///    &quot;Extensions&quot;: [
        ///      &quot;3GP&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;FileTypeDescriptions&quot;: [
        ///      &quot;MPEG-4 v1&quot;
        ///    ],
        ///    &quot;SegmentBytes&quot;: [
        ///      &quot;00 00 00 14 66 74 79 70 69 73 6F 6D&quot;
        ///    ],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FILESIGNATURES_Test {
            get {
                return ResourceManager.GetString("FILESIGNATURES_Test", resourceCulture);
            }
        }
    }
}
